### ISSUE TITLE
解压数据集

### ISSUE THREAD

**Issue by lebron-2016** [gjhhust/XS-VID#1]
尊敬的作者：

您好，

我在解压images.zip时出现了如下问题，请问应该如何解决？
![image](https://github.com/user-attachments/assets/fe1760ae-0ed5-456a-943b-87c1ff060ae6)

感谢！！

**Comment by gjhhust** [comment]
你好，是否下载完全所有的images?(包含images.zip, images.z01, images.z02等等并放在同一个目录下？)，请将目录截图？

**Comment by lebron-2016** [comment]
> 你好，是否下载完全所有的images?(包含images.zip, images.z01, images.z02等等并放在同一个目录下？)，请将目录截图？

是的
![image](https://github.com/user-attachments/assets/f15899ac-8a75-4503-a70b-7d4fa180e7bd)

**Comment by gjhhust** [comment]
我这边尝试解压是正常的，你试试
```
cat images.z01 images.z02 images.z03 images.z04 images.z05 images.zip > full_images.zip
unzip full_images.zip
```

如果还有问题，我尝试不分卷压缩再次上传，这将需要一段时间，文件较大

**Comment by lebron-2016** [comment]
> 我这边尝试解压是正常的，你试试
> 
> ```
> cat images.z01 images.z02 images.z03 images.z04 images.z05 images.zip > full_images.zip
> unzip full_images.zip
> ```
> 
> 如果还有问题，我尝试不分卷压缩再次上传，这将需要一段时间，文件较大

您好，我使用下面的方式解压成功了

```
zip -F images.zip --out out.zip
unzip out.zip
```

感谢您的帮助

**Comment by gjhhust** [comment]
感谢你的尝试，这将会对后续的数据集使用起到帮助！
