### ISSUE TITLE
关于数据集的标签噪声问题

### ISSUE THREAD

**Issue by XianHYe** [gjhhust/XS-VID#2]
可视化发现数据集的一些带有crowd的类别似乎存在比较大的标签噪声？
例如bicycleCrowd和bicycle具体如何界定呢，一组连续的bicycle如果要划分为bicycleCrowd，不同bicycleCrowd目标中包含的数量似乎并不一样，感觉会给训练带来很大困扰。
除此之外想询问一下作者关于ignore类如何处理呢，感觉训练模型去区分ignore类并不是一个很好的选择，能否直接将这些存在明显困惑的类别以及区域在原数据中mask掉呢？

**Comment by gjhhust** [comment]
感谢对XS-VID的关注，我们这把也在继续标注准备不久的将来更新 XS-VIDv2。

  首先我将回答第二个问题，ignore的处理方法我也广泛调研了之前方法的思路，主要包含三种，一种是在计算loss的时候，讲ignore区域的loss不做计算，即不算作正样本或者负样本，不会对模型训练产生影响。第二种是将ignore在训练时不加载，即作为训练负样本。第三种则将ignore区域mask掉，比如用灰色像素覆盖。 

  对于这三种方法，我都经过尝试，XS-VID上发现第三种会明显降低测试指标，第一第二种相差不多。Visdrone2019种我发现第一第三种方式都会明显导致训练效果下降，对数据进行可视化观察后，我认为有以下原因：XS-VID中我们在标注时就尽量注意减少ignore标签的使用，最后ignore标签占比极少，但是ignore区域较大，因此mask会造成大量视频画面无法训练，而第一种第二种则由于ignore的标签较少，对模型的训练效果没有产生很明显的作用。而Visdrone2019中，是由于其标注在初期是ignore，随着视频播放，后期可能会去掉ignore，并且ignore的区域非常大（占据画面的一半以上），而目标主要都是镜头前面较大尺寸的，因此第一种方法使得背景大量干扰没有作为负样本训练，反向的影响了模型的精度，第三种方法不言而喻更难以起到效果。
  
   接下来回答第二个问题，Crowd标签其实是一种类内的ignore标签，本质上也是ignore，我们并不期望模型非常好的分辨出crowd标签，期望的是大量聚集的区域不要对该类的训练造成负面影响即可。
   
   如果有其它问题交流，非常欢迎！

**Comment by XianHYe** [comment]
谢谢你的详细解释。

所以你们在处理时对于ignore和crowd类别都是采取第二种直接不加载的方式吗？如果这个处理方式是你们验证过比较好的，我也试试将我的项目进行这样处理。

还有就是我在xs-vid以及visdrone-vid上训练时还遇到mAP指标先上升后下降的现象，目前一直在寻找原因。一开始猜测是这类数据集的标签噪声很大可能导致训练出现类似过拟合的现象，不知道作者你们是否遇到过这种情况？

**Comment by gjhhust** [comment]
Visdrone2019训练时我按照之前的方法保持一致，没有加载ignore类。XS-VID中，我没有加载ignore类，但是加载了crowd类（crowd中包含了大量与当前类外观一致的内容），因此需要区分。当然这可能也与loss和优化器有关，你们可以进行简单实验！

关于先上升后下降，应该是过拟合了，可能是训练过久？毕竟XS-VID和visdrone2019目前都是几万张图片，数据量并不是很大。我推荐15-24epoch即可。（目前我们团队正在积极扩展XS-VIDv2，扩充了一个数量级的近十万多张图片和一百多个视频，您可以关注一下我们后续的发布，以解决小目标数据量过少的问题）

**Comment by XianHYe** [comment]
> Visdrone2019训练时我按照之前的方法保持一致，没有加载ignore类。XS-VID中，我没有加载ignore类，但是加载了crowd类（crowd中包含了大量与当前类外观一致的内容），因此需要区分。当然这可能也与loss和优化器有关，你们可以进行简单实验！
> 
> 关于先上升后下降，应该是过拟合了，可能是训练过久？毕竟XS-VID和visdrone2019目前都是几万张图片，数据量并不是很大。我推荐15-24epoch即可。（目前我们团队正在积极扩展XS-VIDv2，扩充了一个数量级的近十万多张图片和一百多个视频，您可以关注一下我们后续的发布，以解决小目标数据量过少的问题）

好的，非常感激。
我会关注你们的后续数据集的  ☺️ ☺️ ☺️
